
name: Kalender Liturgi Monthly Scraper

on:
  schedule: # end of month, 17.00 UTC+0 is 00.00 UTC+7
    - cron : ' 0 17  31     1,3,5,7,8,10,12  * '
    - cron : ' 0 17  30     4,6,9,11         * '
    - cron : ' 0 17  28,29  2                * '
  workflow_dispatch: # Allow manual run workflow

jobs:
  scrape:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3
        with: 
          ref: gh-pages
      - name: Setup
        run: |
          mkdir -p kalender/api
          git config --global user.name '${{ github.actor }}'
          git config --global user.email '${{ github.actor }}@users.noreply.github.com'
          echo "YEARMONTH=$(date -d '+7 hour 7 second' +'%Y-%m')" >> $GITHUB_ENV
      - name: Clone akolites/kalender-liturgi
        working-directory: /tmp
        run: |
          git clone --single-branch https://github.com/akolites/kalender-liturgi.git 
      - name: Install Scraper
        working-directory: /tmp/kalender-liturgi
        run: |
          make install
      - name: Scrape # executed at 00.00 H+0 == 17.00 H-1 : the provider server time.
        working-directory: /tmp/kalender-liturgi
        run: |
          YEARMONTH=${{ env.YEARMONTH }} make action
      - name: Commit and Push
        run: |
          cp -rf /tmp/kalender-liturgi/api/* ./kalender/api/
          git add ./kalender/api
          git commit -m "feat/kalender: [automated] date:${{ env.YEARMONTH }}" \
          -m "from ref:${GITHUB_SHA}"
          git push